In [25]:
import pandas as pd 
Texas = pd.read_csv("Texas_emissions.csv")
Texas

,"Texas Emissions, Transportation Sector, MMT CO2 eq.",1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Fossil fuel combustion: carbon dioxide,132.845339,126.155292,130.655360,130.774951,137.744756,134.482530,147.416355,147.748467,153.821000,...,164.210905,169.597786,182.402242,183.375068,184.970026,191.275544,195.319786,203.452957,207.300009,179.818269
1,Use of fluorinated gases,0.000000,0.000000,0.101253,0.443948,1.086869,1.727666,2.513664,3.336230,3.927912,...,8.036891,5.940122,5.593783,5.851211,5.598296,5.258897,4.895110,4.707792,4.513393,4.319930
2,Fossil fuel combustion: other greenhouse gases,3.617258,3.729063,3.950554,4.081505,4.316625,4.369733,4.492583,4.769181,4.867099,...,2.235697,1.968690,1.854894,1.708949,1.696729,1.650720,1.522944,1.456156,1.527708,1.295333
3,Other transportation categories,0.797563,0.713549,0.727473,0.740724,0.774222,0.760904,0.738505,0.780142,0.816667,...,1.075974,0.994449,1.088418,1.228868,1.319676,1.259944,1.164966,1.151109,1.134898,0.965121
4,Total,137.260161,130.597903,135.434640,136.041129,143.922474,141.340834,155.161106,156.634020,163.432678,...,175.559468,178.501047,190.939337,192.164096,193.584726,199.445105,202.902806,210.768014,214.476009,186.398654

In [24]:
texas_recent = Texas[['Texas Emissions, Transportation Sector, MMT CO2 eq.',"2015","2016","2017","2018","2019","2020"]]
texas_recent

,"Texas Emissions, Transportation Sector, MMT CO2 eq.",2015,2016,2017,2018,2019,2020
0,Fossil fuel combustion: carbon dioxide,184.970026,191.275544,195.319786,203.452957,207.300009,179.818269
1,Use of fluorinated gases,5.598296,5.258897,4.895110,4.707792,4.513393,4.319930
2,Fossil fuel combustion: other greenhouse gases,1.696729,1.650720,1.522944,1.456156,1.527708,1.295333
3,Other transportation categories,1.319676,1.259944,1.164966,1.151109,1.134898,0.965121
4,Total,193.584726,199.445105,202.902806,210.768014,214.476009,186.398654

In [38]:
National = pd.read_csv("national_emissions.csv")
National

,"U.S. Emissions, Transportation Sector, MMT CO2 eq.",1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Fossil fuel combustion: carbon dioxide,1468.943894,1422.327405,1477.643426,1508.607034,1553.947354,1580.677858,1627.363105,1643.515554,1678.920338,...,1670.546303,1659.564856,1669.110613,1707.317307,1718.207954,1757.638404,1779.977191,1812.760635,1813.754773,1572.034241
1,Use of fluorinated gases,0.000000,0.000000,1.168982,5.097346,12.406418,19.613489,28.373833,37.426521,43.762914,...,62.433824,57.124682,51.583412,48.753876,46.336493,43.298741,40.139715,38.460744,36.742691,35.034954
2,Fossil fuel combustion: other greenhouse gases,45.651720,47.385595,50.271427,52.188277,53.997098,55.433732,56.550893,57.327820,57.490730,...,25.634961,23.114447,21.178300,19.289766,17.903407,16.725967,15.495189,14.290525,14.959802,12.527177
3,Other transportation categories,11.838675,10.590906,10.797881,10.995035,11.491990,11.294702,10.961335,11.579435,12.121996,...,9.980272,9.108246,9.643206,10.046125,10.951515,10.382451,9.550515,9.214391,8.833871,8.022182
4,Total,1526.434289,1480.303906,1539.881716,1576.887693,1631.842860,1667.019781,1723.249166,1749.849331,1792.295979,...,1768.595360,1748.912231,1751.515531,1785.407075,1793.399368,1828.045564,1845.162610,1874.726295,1874.291138,1627.618555

In [37]:
natl_recent = National[['U.S. Emissions, Transportation Sector, MMT CO2 eq.',"2015","2016","2017","2018","2019","2020"]]
natl_recent

,"U.S. Emissions, Transportation Sector, MMT CO2 eq.",2015,2016,2017,2018,2019,2020
0,Fossil fuel combustion: carbon dioxide,1718.207954,1757.638404,1779.977191,1812.760635,1813.754773,1572.034241
1,Use of fluorinated gases,46.336493,43.298741,40.139715,38.460744,36.742691,35.034954
2,Fossil fuel combustion: other greenhouse gases,17.903407,16.725967,15.495189,14.290525,14.959802,12.527177
3,Other transportation categories,10.951515,10.382451,9.550515,9.214391,8.833871,8.022182
4,Total,1793.399368,1828.045564,1845.162610,1874.726295,1874.291138,1627.618555